
version: '3'
services:
  mysql:
    image: mysql:5.7.12
    restart: always
    environment:
      MYSQL_DATABASE: marinatest
      MYSQL_USER: marina
      MYSQL_PASSWORD: marina
      MYSQL_ROOT_PASSWORD: marina
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: marina
    links:
      - mysql
  minio:
    image: minio/minio:RELEASE.2019-05-02T19-07-09Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
    volumes:
      - "./minio-data:/data"
    command: server /data
  minio_bucket:
    image: minio/mc:RELEASE.2019-05-01T23-27-44Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc rm -r --force myminio/marina;
      /usr/bin/mc mb myminio/marina;
      /usr/bin/mc policy download myminio/marina"
volumes:
  mysql: ~
