CREATE TABLE `organizations` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

CREATE TABLE `repository` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`org_id` BIGINT UNSIGNED NOT NULL,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	INDEX (`name`),
	FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`)
);

CREATE TABLE `image` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`digest` VARCHAR(255) NOT NULL,
	`repo_id` BIGINT UNSIGNED NOT NULL,
	`manifest` JSON NOT NULL,
	`manifest_type` VARCHAR(255) NOT NULL,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	FOREIGN KEY (`repo_id`) REFERENCES `repository` (`id`)
);

CREATE TABLE `tag` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`image_id` BIGINT UNSIGNED NOT NULL,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	FOREIGN KEY (`image_id`) REFERENCES `image` (`id`)
);

CREATE TABLE `blob` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`digest` VARCHAR(255) NOT NULL,
	`repo_id` BIGINT UNSIGNED NOT NULL,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	FOREIGN KEY (`repo_id`) REFERENCES `repository` (`id`)
);

CREATE TABLE `upload` (
	`uuid` CHAR(36) PRIMARY KEY,
	`done` BOOLEAN NOT NULL DEFAULT FALSE,
	`_last_updated` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

CREATE TABLE `upload_chunk` (
	`uuid` CHAR(36),
	`range_start` BIGINT,
	`range_end` BIGINT,
	PRIMARY KEY(`uuid`, `range_start`, `range_end`)
);

