version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/golang:1.12
      - image: mysql:5.7.12
        environment:
          MYSQL_DATABASE: marinatest
          MYSQL_USER: marina
          MYSQL_PASSWORD: marina
          MYSQL_ROOT_PASSWORD: marina
    working_directory: /go/src/github.com/ryantking/marina
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: GO111MODULE=on go mod vendor
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
      - run:
          name: Run unit tests
          command: go test -race -covermode=atomic -coverprofile=coverage.txt ./pkg/...
      - run:
          name: Upload results to codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test:
    jobs:
      - unit_tests
